import type { TarotCard } from '@/types';

export const tarotDeck: TarotCard[] = [
  {
    id: 0,
    name: 'card_0_name',
    meaning_up: 'card_0_meaning_up',
    meaning_rev: 'card_0_meaning_rev',
    desc: 'card_0_desc',
    yesNo: 'Yes',
    imageName: 'the fool',
    imageUrl: '/major/00-The-Fool.jpg',
  },
  {
    id: 1,
    name: 'card_1_name',
    meaning_up: 'card_1_meaning_up',
    meaning_rev: 'card_1_meaning_rev',
    desc: 'card_1_desc',
    yesNo: 'Yes',
    imageName: 'magician staff',
    imageUrl: '/major/01-The-Magician.jpg',
  },
  {
    id: 2,
    name: 'card_2_name',
    meaning_up: 'card_2_meaning_up',
    meaning_rev: 'card_2_meaning_rev',
    desc: 'card_2_desc',
    yesNo: 'Maybe',
    imageName: 'priestess moon',
    imageUrl: '/major/02-The-High-Priestess.jpg',
  },
  {
    id: 3,
    name: 'card_3_name',
    meaning_up: 'card_3_meaning_up',
    meaning_rev: 'card_3_meaning_rev',
    desc: 'card_3_desc',
    yesNo: 'Yes',
    imageName: 'empress nature',
    imageUrl: '/major/03-The-Empress.jpg',
  },
  {
    id: 4,
    name: 'card_4_name',
    meaning_up: 'card_4_meaning_up',
    meaning_rev: 'card_4_meaning_rev',
    desc: 'card_4_desc',
    yesNo: 'Yes',
    imageName: 'emperor throne',
    imageUrl: '/major/04-The-Emperor.jpg',
  },
  {
    id: 5,
    name: 'card_5_name',
    meaning_up: 'card_5_meaning_up',
    meaning_rev: 'card_5_meaning_rev',
    desc: 'card_5_desc',
    yesNo: 'Maybe',
    imageName: 'hierophant keys',
    imageUrl: '/major/05-The-Hierophant.jpg',
  },
  {
    id: 6,
    name: 'card_6_name',
    meaning_up: 'card_6_meaning_up',
    meaning_rev: 'card_6_meaning_rev',
    desc: 'card_6_desc',
    yesNo: 'Yes',
    imageName: 'lovers couple',
    imageUrl: '/major/06-The-Lovers.jpg',
  },
  {
    id: 7,
    name: 'card_7_name',
    meaning_up: 'card_7_meaning_up',
    meaning_rev: 'card_7_meaning_rev',
    desc: 'card_7_desc',
    yesNo: 'Yes',
    imageName: 'chariot horses',
    imageUrl: '/major/07-The-Chariot.jpg',
  },
  {
    id: 8,
    name: 'card_8_name',
    meaning_up: 'card_8_meaning_up',
    meaning_rev: 'card_8_meaning_rev',
    desc: 'card_8_desc',
    yesNo: 'Yes',
    imageName: 'strength lion',
    imageUrl: '/major/08-Strength.jpg',
  },
  {
    id: 9,
    name: 'card_9_name',
    meaning_up: 'card_9_meaning_up',
    meaning_rev: 'card_9_meaning_rev',
    desc: 'card_9_desc',
    yesNo: 'Maybe',
    imageName: 'hermit lantern',
    imageUrl: '/major/09-The-Hermit.jpg',
  },
  {
    id: 10,
    name: 'card_10_name',
    meaning_up: 'card_10_meaning_up',
    meaning_rev: 'card_10_meaning_rev',
    desc: 'card_10_desc',
    yesNo: 'Yes',
    imageName: 'wheel fortune',
    imageUrl: '/major/10-Wheel-of-Fortune.jpg',
  },
  {
    id: 11,
    name: 'card_11_name',
    meaning_up: 'card_11_meaning_up',
    meaning_rev: 'card_11_meaning_rev',
    desc: 'card_11_desc',
    yesNo: 'Maybe',
    imageName: 'justice scales',
    imageUrl: '/major/11-Justice.jpg',
  },
  {
    id: 12,
    name: 'card_12_name',
    meaning_up: 'card_12_meaning_up',
    meaning_rev: 'card_12_meaning_rev',
    desc: 'card_12_desc',
    yesNo: 'Maybe',
    imageName: 'hanged man',
    imageUrl: '/major/12-The-Hanged-Man.jpg',
  },
  {
    id: 13,
    name: 'card_13_name',
    meaning_up: 'card_13_meaning_up',
    meaning_rev: 'card_13_meaning_rev',
    desc: 'card_13_desc',
    yesNo: 'No',
    imageName: 'death skeleton',
    imageUrl: '/major/13-Death.jpg',
  },
  {
    id: 14,
    name: 'card_14_name',
    meaning_up: 'card_14_meaning_up',
    meaning_rev: 'card_14_meaning_rev',
    desc: 'card_14_desc',
    yesNo: 'Yes',
    imageName: 'temperance angel',
    imageUrl: '/major/14-Temperance.jpg',
  },
  {
    id: 15,
    name: 'card_15_name',
    meaning_up: 'card_15_meaning_up',
    meaning_rev: 'card_15_meaning_rev',
    desc: 'card_15_desc',
    yesNo: 'No',
    imageName: 'devil chains',
    imageUrl: '/major/15-The-Devil.jpg',
  },
  {
    id: 16,
    name: 'card_16_name',
    meaning_up: 'card_16_meaning_up',
    meaning_rev: 'card_16_meaning_rev',
    desc: 'card_16_desc',
    yesNo: 'No',
    imageName: 'tower lightning',
    imageUrl: '/major/16-The-Tower.jpg',
  },
  {
    id: 17,
    name: 'card_17_name',
    meaning_up: 'card_17_meaning_up',
    meaning_rev: 'card_17_meaning_rev',
    desc: 'card_17_desc',
    yesNo: 'Yes',
    imageName: 'star sky',
    imageUrl: '/major/17-The-Star.jpg',
  },
  {
    id: 18,
    name: 'card_18_name',
    meaning_up: 'card_18_meaning_up',
    meaning_rev: 'card_18_meaning_rev',
    desc: 'card_18_desc',
    yesNo: 'No',
    imageName: 'moon sky',
    imageUrl: '/major/18-The-Moon.jpg',
  },
  {
    id: 19,
    name: 'card_19_name',
    meaning_up: 'card_19_meaning_up',
    meaning_rev: 'card_19_meaning_rev',
    desc: 'card_19_desc',
    yesNo: 'Yes',
    imageName: 'sun child',
    imageUrl: '/major/19-The-Sun.jpg',
  },
  {
    id: 20,
    name: 'card_20_name',
    meaning_up: 'card_20_meaning_up',
    meaning_rev: 'card_20_meaning_rev',
    desc: 'card_20_desc',
    yesNo: 'Maybe',
    imageName: 'judgement angel',
    imageUrl: '/major/20-Judgement.jpg',
  },
  {
    id: 21,
    name: 'card_21_name',
    meaning_up: 'card_21_meaning_up',
    meaning_rev: 'card_21_meaning_rev',
    desc: 'card_21_desc',
    yesNo: 'Yes',
    imageName: 'world dancer',
    imageUrl: '/major/21-The-World.jpg',
  },

  {
    id: 22,
    name: 'card_22_name',
    meaning_up: 'card_22_meaning_up',
    meaning_rev: 'card_22_meaning_rev',
    desc: 'card_22_desc',
    yesNo: 'Yes',
    imageName: 'ace cups',
    imageUrl: '/cups/Ace-of-Cups.jpg',
  },
  {
    id: 23,
    name: 'card_23_name',
    meaning_up: 'card_23_meaning_up',
    meaning_rev: 'card_23_meaning_rev',
    desc: 'card_23_desc',
    yesNo: 'Yes',
    imageName: 'two cups',
    imageUrl: '/cups/2-of-Cups.jpg',
  },
  {
    id: 24,
    name: 'card_24_name',
    meaning_up: 'card_24_meaning_up',
    meaning_rev: 'card_24_meaning_rev',
    desc: 'card_24_desc',
    yesNo: 'Yes',
    imageName: 'ace swords',
    imageUrl: '/swords/Ace-of-Swords.jpg',
  },
  {
    id: 25,
    name: 'card_25_name',
    meaning_up: 'card_25_meaning_up',
    meaning_rev: 'card_25_meaning_rev',
    desc: 'card_25_desc',
    yesNo: 'No',
    imageName: 'nine swords',
    imageUrl: '/swords/9-of-Swords.jpg',
  },
  {
    id: 26,
    name: 'card_26_name',
    meaning_up: 'card_26_meaning_up',
    meaning_rev: 'card_26_meaning_rev',
    desc: 'card_26_desc',
    yesNo: 'Maybe',
    imageName: 'six cups',
    imageUrl: '/cups/6-of-Cups.jpg',
  },
  {
    id: 27,
    name: 'card_27_name',
    meaning_up: 'card_27_meaning_up',
    meaning_rev: 'card_27_meaning_rev',
    desc: 'card_27_desc',
    yesNo: 'Yes',
    imageName: 'king swords',
    imageUrl: '/swords/King-of-Swords.jpg',
  },
  {
    id: 28,
    name: 'card_28_name',
    meaning_up: 'card_28_meaning_up',
    meaning_rev: 'card_28_meaning_rev',
    desc: 'card_28_desc',
    yesNo: 'Maybe',
    imageName: 'four swords',
    imageUrl: '/swords/4-of-Swords.jpg',
  },
  {
    id: 29,
    name: 'card_29_name',
    meaning_up: 'card_29_meaning_up',
    meaning_rev: 'card_29_meaning_rev',
    desc: 'card_29_desc',
    yesNo: 'No',
    imageName: 'page pentacles',
    imageUrl: '/pentacles/Page-of-Pentacles.jpg',
  },
  {
    id: 30,
    name: 'card_30_name',
    meaning_up: 'card_30_meaning_up',
    meaning_rev: 'card_30_meaning_rev',
    desc: 'card_30_desc',
    yesNo: 'Yes',
    imageName: 'seven wands',
    imageUrl: '/wands/7-of-Wands.jpg',
  },
  {
    id: 31,
    name: 'card_31_name',
    meaning_up: 'card_31_meaning_up',
    meaning_rev: 'card_31_meaning_rev',
    desc: 'card_31_desc',
    yesNo: 'Yes',
    imageName: 'queen wands',
    imageUrl: '/wands/Queen-of-Wands.jpg',
  },
  {
    id: 32,
    name: 'card_32_name',
    meaning_up: 'card_32_meaning_up',
    meaning_rev: 'card_32_meaning_rev',
    desc: 'card_32_desc',
    yesNo: 'No',
    imageName: 'two swords',
    imageUrl: '/swords/2-of-Swords.jpg',
  },
  {
    id: 33,
    name: 'card_33_name',
    meaning_up: 'card_33_meaning_up',
    meaning_rev: 'card_33_meaning_rev',
    desc: 'card_33_desc',
    yesNo: 'Maybe',
    imageName: 'eight cups',
    imageUrl: '/cups/8-of-Cups.jpg',
  },
  {
    id: 34,
    name: 'card_34_name',
    meaning_up: 'card_34_meaning_up',
    meaning_rev: 'card_34_meaning_rev',
    desc: 'card_34_desc',
    yesNo: 'No',
    imageName: 'four pentacles',
    imageUrl: '/pentacles/4-of-Pentacles.jpg',
  },
  {
    id: 35,
    name: 'card_35_name',
    meaning_up: 'card_35_meaning_up',
    meaning_rev: 'card_35_meaning_rev',
    desc: 'card_35_desc',
    yesNo: 'Yes',
    imageName: 'three cups',
    imageUrl: '/cups/3-of-Cups.jpg',
  },
  {
    id: 36,
    name: 'card_36_name',
    meaning_up: 'card_36_meaning_up',
    meaning_rev: 'card_36_meaning_rev',
    desc: 'card_36_desc',
    yesNo: 'Yes',
    imageName: 'ace wands',
    imageUrl: '/wands/Ace-of-Wands.jpg',
  },
  {
    id: 37,
    name: 'card_37_name',
    meaning_up: 'card_37_meaning_up',
    meaning_rev: 'card_37_meaning_rev',
    desc: 'card_37_desc',
    yesNo: 'Maybe',
    imageName: 'two wands',
    imageUrl: '/wands/2-of-Wands.jpg',
  },
  {
    id: 38,
    name: 'card_38_name',
    meaning_up: 'card_38_meaning_up',
    meaning_rev: 'card_38_meaning_rev',
    desc: 'card_38_desc',
    yesNo: 'Yes',
    imageName: 'three wands',
    imageUrl: '/wands/3-of-Wands.jpg',
  },
  {
    id: 39,
    name: 'card_39_name',
    meaning_up: 'card_39_meaning_up',
    meaning_rev: 'card_39_meaning_rev',
    desc: 'card_39_desc',
    yesNo: 'Yes',
    imageName: 'four wands',
    imageUrl: '/wands/4-of-Wands.jpg',
  },
  {
    id: 40,
    name: 'card_40_name',
    meaning_up: 'card_40_meaning_up',
    meaning_rev: 'card_40_meaning_rev',
    desc: 'card_40_desc',
    yesNo: 'No',
    imageName: 'five wands',
    imageUrl: '/wands/5-of-Wands.jpg',
  },
  {
    id: 41,
    name: 'card_41_name',
    meaning_up: 'card_41_meaning_up',
    meaning_rev: 'card_41_meaning_rev',
    desc: 'card_41_desc',
    yesNo: 'Yes',
    imageName: 'six wands',
    imageUrl: '/wands/6-of-Wands.jpg',
  },
  {
    id: 42,
    name: 'card_42_name',
    meaning_up: 'card_42_meaning_up',
    meaning_rev: 'card_42_meaning_rev',
    desc: 'card_42_desc',
    yesNo: 'Yes',
    imageName: 'eight wands',
    imageUrl: '/wands/8-of-Wands.jpg',
  },
  {
    id: 43,
    name: 'card_43_name',
    meaning_up: 'card_43_meaning_up',
    meaning_rev: 'card_43_meaning_rev',
    desc: 'card_43_desc',
    yesNo: 'Maybe',
    imageName: 'nine wands',
    imageUrl: '/wands/9-of-Wands.jpg',
  },
  {
    id: 44,
    name: 'card_44_name',
    meaning_up: 'card_44_meaning_up',
    meaning_rev: 'card_44_meaning_rev',
    desc: 'card_44_desc',
    yesNo: 'No',
    imageName: 'ten wands',
    imageUrl: '/wands/10-of-Wands.jpg',
  },
  {
    id: 45,
    name: 'card_45_name',
    meaning_up: 'card_45_meaning_up',
    meaning_rev: 'card_45_meaning_rev',
    desc: 'card_45_desc',
    yesNo: 'Yes',
    imageName: 'page wands',
    imageUrl: '/wands/Page-of-Wands.jpg',
  },
  {
    id: 46,
    name: 'card_46_name',
    meaning_up: 'card_46_meaning_up',
    meaning_rev: 'card_46_meaning_rev',
    desc: 'card_46_desc',
    yesNo: 'Yes',
    imageName: 'knight wands',
    imageUrl: '/wands/Knight-of-Wands.jpg',
  },
  {
    id: 47,
    name: 'card_47_name',
    meaning_up: 'card_47_meaning_up',
    meaning_rev: 'card_47_meaning_rev',
    desc: 'card_47_desc',
    yesNo: 'Yes',
    imageName: 'king wands',
    imageUrl: '/wands/King-of-Wands.jpg',
  },
  {
    id: 48,
    name: 'card_48_name',
    meaning_up: 'card_48_meaning_up',
    meaning_rev: 'card_48_meaning_rev',
    desc: 'card_48_desc',
    yesNo: 'No',
    imageName: 'four cups',
    imageUrl: '/cups/4-of-Cups.jpg',
  },
  {
    id: 49,
    name: 'card_49_name',
    meaning_up: 'card_49_meaning_up',
    meaning_rev: 'card_49_meaning_rev',
    desc: 'card_49_desc',
    yesNo: 'No',
    imageName: 'five cups',
    imageUrl: '/cups/5-of-Cups.jpg',
  },
  {
    id: 50,
    name: 'card_50_name',
    meaning_up: 'card_50_meaning_up',
    meaning_rev: 'card_50_meaning_rev',
    desc: 'card_50_desc',
    yesNo: 'Maybe',
    imageName: 'seven cups',
    imageUrl: '/cups/7-of-Cups.jpg',
  },
  {
    id: 51,
    name: 'card_51_name',
    meaning_up: 'card_51_meaning_up',
    meaning_rev: 'card_51_meaning_rev',
    desc: 'card_51_desc',
    yesNo: 'Yes',
    imageName: 'nine cups',
    imageUrl: '/cups/9-of-Cups.jpg',
  },
  {
    id: 52,
    name: 'card_52_name',
    meaning_up: 'card_52_meaning_up',
    meaning_rev: 'card_52_meaning_rev',
    desc: 'card_52_desc',
    yesNo: 'Yes',
    imageName: 'ten cups',
    imageUrl: '/cups/10-of-Cups.jpg',
  },
  {
    id: 53,
    name: 'card_53_name',
    meaning_up: 'card_53_meaning_up',
    meaning_rev: 'card_53_meaning_rev',
    desc: 'card_53_desc',
    yesNo: 'Yes',
    imageName: 'page cups',
    imageUrl: '/cups/Page-of-Cups.jpg',
  },
  {
    id: 54,
    name: 'card_54_name',
    meaning_up: 'card_54_meaning_up',
    meaning_rev: 'card_54_meaning_rev',
    desc: 'card_54_desc',
    yesNo: 'Yes',
    imageName: 'knight cups',
    imageUrl: '/cups/Knight-of-Cups.jpg',
  },
  {
    id: 55,
    name: 'card_55_name',
    meaning_up: 'card_55_meaning_up',
    meaning_rev: 'card_55_meaning_rev',
    desc: 'card_55_desc',
    yesNo: 'Yes',
    imageName: 'queen cups',
    imageUrl: '/cups/Queen-of-Cups.jpg',
  },
  {
    id: 56,
    name: 'card_56_name',
    meaning_up: 'card_56_meaning_up',
    meaning_rev: 'card_56_meaning_rev',
    desc: 'card_56_desc',
    yesNo: 'Yes',
    imageName: 'king cups',
    imageUrl: '/cups/King-of-Cups.jpg',
  },
  {
    id: 57,
    name: 'card_57_name',
    meaning_up: 'card_57_meaning_up',
    meaning_rev: 'card_57_meaning_rev',
    desc: 'card_57_desc',
    yesNo: 'No',
    imageName: 'three swords',
    imageUrl: '/swords/3-of-Swords.jpg',
  },
  {
    id: 58,
    name: 'card_58_name',
    meaning_up: 'card_58_meaning_up',
    meaning_rev: 'card_58_meaning_rev',
    desc: 'card_58_desc',
    yesNo: 'No',
    imageName: 'five swords',
    imageUrl: '/swords/5-of-Swords.jpg',
  },
  {
    id: 59,
    name: 'card_59_name',
    meaning_up: 'card_59_meaning_up',
    meaning_rev: 'card_59_meaning_rev',
    desc: 'card_59_desc',
    yesNo: 'Yes',
    imageName: 'six swords',
    imageUrl: '/swords/6-of-Swords.jpg',
  },
  {
    id: 60,
    name: 'card_60_name',
    meaning_up: 'card_60_meaning_up',
    meaning_rev: 'card_60_meaning_rev',
    desc: 'card_60_desc',
    yesNo: 'No',
    imageName: 'seven swords',
    imageUrl: '/swords/7-of-Swords.jpg',
  },
  {
    id: 61,
    name: 'card_61_name',
    meaning_up: 'card_61_meaning_up',
    meaning_rev: 'card_61_meaning_rev',
    desc: 'card_61_desc',
    yesNo: 'No',
    imageName: 'eight swords',
    imageUrl: '/swords/8-of-Swords.jpg',
  },
  {
    id: 62,
    name: 'card_62_name',
    meaning_up: 'card_62_meaning_up',
    meaning_rev: 'card_62_meaning_rev',
    desc: 'card_62_desc',
    yesNo: 'No',
    imageName: 'ten swords',
    imageUrl: '/swords/10-of-Swords.jpg',
  },
  {
    id: 63,
    name: 'card_63_name',
    meaning_up: 'card_63_meaning_up',
    meaning_rev: 'card_63_meaning_rev',
    desc: 'card_63_desc',
    yesNo: 'Yes',
    imageName: 'page swords',
    imageUrl: '/swords/Page-of-Swords.jpg',
  },
  {
    id: 64,
    name: 'card_64_name',
    meaning_up: 'card_64_meaning_up',
    meaning_rev: 'card_64_meaning_rev',
    desc: 'card_64_desc',
    yesNo: 'Maybe',
    imageName: 'knight swords',
    imageUrl: '/swords/Knight-of-Swords.jpg',
  },
  {
    id: 65,
    name: 'card_65_name',
    meaning_up: 'card_65_meaning_up',
    meaning_rev: 'card_65_meaning_rev',
    desc: 'card_65_desc',
    yesNo: 'Yes',
    imageName: 'queen swords',
    imageUrl: '/swords/Queen-of-Swords.jpg',
  },
  {
    id: 66,
    name: 'card_66_name',
    meaning_up: 'card_66_meaning_up',
    meaning_rev: 'card_66_meaning_rev',
    desc: 'card_66_desc',
    yesNo: 'Yes',
    imageName: 'king swords',
    imageUrl: '/swords/King-of-Swords.jpg',
  },
  {
    id: 67,
    name: 'card_67_name',
    meaning_up: 'card_67_meaning_up',
    meaning_rev: 'card_67_meaning_rev',
    desc: 'card_67_desc',
    yesNo: 'Yes',
    imageName: 'ace pentacles',
    imageUrl: '/pentacles/Ace-of-Pentacles.jpg',
  },
  {
    id: 68,
    name: 'card_68_name',
    meaning_up: 'card_68_meaning_up',
    meaning_rev: 'card_68_meaning_rev',
    desc: 'card_68_desc',
    yesNo: 'Maybe',
    imageName: 'two pentacles',
    imageUrl: '/pentacles/2-of-Pentacles.jpg',
  },
  {
    id: 69,
    name: 'card_69_name',
    meaning_up: 'card_69_meaning_up',
    meaning_rev: 'card_69_meaning_rev',
    desc: 'card_69_desc',
    yesNo: 'Yes',
    imageName: 'three pentacles',
    imageUrl: '/pentacles/3-of-Pentacles.jpg',
  },
  {
    id: 70,
    name: 'card_70_name',
    meaning_up: 'card_70_meaning_up',
    meaning_rev: 'card_70_meaning_rev',
    desc: 'card_70_desc',
    yesNo: 'No',
    imageName: 'five pentacles',
    imageUrl: '/pentacles/5-of-Pentacles.jpg',
  },
  {
    id: 71,
    name: 'card_71_name',
    meaning_up: 'card_71_meaning_up',
    meaning_rev: 'card_71_meaning_rev',
    desc: 'card_71_desc',
    yesNo: 'Yes',
    imageName: 'six pentacles',
    imageUrl: '/pentacles/6-of-Pentacles.jpg',
  },
  {
    id: 72,
    name: 'card_72_name',
    meaning_up: 'card_72_meaning_up',
    meaning_rev: 'card_72_meaning_rev',
    desc: 'card_72_desc',
    yesNo: 'Maybe',
    imageName: 'seven pentacles',
    imageUrl: '/pentacles/7-of-Pentacles.jpg',
  },
  {
    id: 73,
    name: 'card_73_name',
    meaning_up: 'card_73_meaning_up',
    meaning_rev: 'card_73_meaning_rev',
    desc: 'card_73_desc',
    yesNo: 'Yes',
    imageName: 'eight pentacles',
    imageUrl: '/pentacles/8-of-Pentacles.jpg',
  },
  {
    id: 74,
    name: 'card_74_name',
    meaning_up: 'card_74_meaning_up',
    meaning_rev: 'card_74_meaning_rev',
    desc: 'card_74_desc',
    yesNo: 'Yes',
    imageName: 'nine pentacles',
    imageUrl: '/pentacles/9-of-Pentacles.jpg',
  },
  {
    id: 75,
    name: 'card_75_name',
    meaning_up: 'card_75_meaning_up',
    meaning_rev: 'card_75_meaning_rev',
    desc: 'card_75_desc',
    yesNo: 'Yes',
    imageName: 'ten pentacles',
    imageUrl: '/pentacles/10-of-Pentacles.jpg',
  },
  {
    id: 76,
    name: 'card_76_name',
    meaning_up: 'card_76_meaning_up',
    meaning_rev: 'card_76_meaning_rev',
    desc: 'card_76_desc',
    yesNo: 'Yes',
    imageName: 'page pentacles',
    imageUrl: '/pentacles/Page-of-Pentacles.jpg',
  },
  {
    id: 77,
    name: 'card_77_name',
    meaning_up: 'card_77_meaning_up',
    meaning_rev: 'card_77_meaning_rev',
    desc: 'card_77_desc',
    yesNo: 'Maybe',
    imageName: 'knight pentacles',
    imageUrl: '/pentacles/Knight-of-Pentacles.jpg',
  },
  {
    id: 78,
    name: 'card_78_name',
    meaning_up: 'card_78_meaning_up',
    meaning_rev: 'card_78_meaning_rev',
    desc: 'card_78_desc',
    yesNo: 'Yes',
    imageName: 'queen pentacles',
    imageUrl: '/pentacles/Queen-of-Pentacles.jpg',
  },
  {
    id: 79,
    name: 'card_79_name',
    meaning_up: 'card_79_meaning_up',
    meaning_rev: 'card_79_meaning_rev',
    desc: 'card_79_desc',
    yesNo: 'Yes',
    imageName: 'king pentacles',
    imageUrl: '/pentacles/King-of-Pentacles.jpg',
  },
];

// Correcting duplicate IDs and ensuring unique entries
const uniqueCardMap = new Map<number, TarotCard>();
tarotDeck.forEach((card) => {
  if (!uniqueCardMap.has(card.id)) {
    uniqueCardMap.set(card.id, card);
  }
});

// Ensure we have all cards from 0 to 78 in order
export const fullTarotDeck: TarotCard[] = Array.from(uniqueCardMap.values())
  .sort((a, b) => a.id - b.id)
  .filter((card) => card.id >= 0 && card.id <= 78);

// For simplicity, we'll use the provided subset, but ensure no duplicates in the actual app logic if drawing from this 'fullTarotDeck'
// The initial request had some duplicate card names with different IDs (e.g. Wheel of Fortune, Chariot)
// For now, the `tarotDeck` provided is used as is, assuming the IDs are what matter for uniqueness if names repeat.
// The `fullTarotDeck` above is a de-duplicated version by ID, which is more robust.
// We will use `fullTarotDeck` for drawing.
